
name: Sample Workflow

on:
    push:
        branches:
            - main

jobs:
    learning:
        runs-on: ubuntu-latest
        steps:
            - name: learning
              run: "echo My name is Krishna Kishore"
            - name: list env
              run: printenv

              